### PR TITLE
chore: improve testing

### PR DESCRIPTION
**Pull request by pedrovalido**
A few tests are currently:
- outdated/broken
- not covering the case where the the contract is deployed with the wrong parameters
- not covering the `all` function pagination

### CODE REVIEW

**Comment by stas** [comment]
cc @ethzoomer if you could take a look as well please

**Comment by pedrovalido** [comment]
> This looks great! Not sure why the tests are going wild though...

Trying to figure it out as well...

**Review by pedrovalido — COMMENTED** [review]
ty ty @ethzoomer for the fixes. LGTM. 
Please review the other parts and we can merge this

**Review by stas — APPROVED** [review]
:shipit: 

Thank you!

**Pull request merged**
